version: "3.8"
services:
  mysql:
    # コンテナの設定
    image: mariadb:latest
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    ports:
      - 4306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
